var coffeeProductsArray = [
   {
      Id: "coffeebeans1",
      Name: "Ethereal",
      Variety: "Blue Mountain",
      Region: "Africa",
      Type: "Regular",
      Price: 10, 
   }, 
   {
      Id: "coffeebeans2",
      Name: "Intoxicating",
      Variety: "Pacas",
      Region: "Latin America",
      Type: "Regular",
      Price: 12, 
   }, 
   {
      Id: "coffeebeans3",
      Name: "Bella",
      Variety: "Catuai",
      Region: "Latin America",
      Type: "Decaf",
      Price: 12, 
   },
   {
      Id: "coffeebeans4",
      Name: "Tropic Fever",
      Variety: "Sulawesi Toraja Kalossi",
      Region: "Oceania",
      Type: "Regular",
      Price: 9,      
   }, 
   {
      Id: "coffeebeans5",
      Name: "Dynamo",
      Variety: "Ethiopian Sidamo",
      Region: "Africa",
      Type: "Regular",
      Price: 10,    
   },
   {
      Id: "coffeebeans6",
      Name: "Charmer",
      Variety: "Mundo Novo",
      Region: "Latin America",
      Type: "Decaf",
      Price: 15,        
   }, 
   {
      Id: "coffeebeans7",
      Name: "True Roast",
      Variety: "Mayagüez",
      Region: "Africa",
      Type: "Regular",
      Price: 10,  
   },              
   {
      Id: "coffeebeans8",
      Name: "Caffe",
      Variety: "Java",
      Region: "Oceania",
      Type: "Decaf",
      Price: 8,            
   }, 
   {
      Id: "coffeebeans9",
      Name: "Coastal Rush",
      Variety: "Mocha",
      Region: "Asia",
      Type: "Regular",
      Price: 11,        
   }, 
]
